"""
ui/theme.py
───────────
Colour definitions. The active palette is selected by colour_mode,
which is set at startup based on the saved config
"""

colour_mode = "new"

FONT = "Consolas"
TITLE_PREFIX = "◈"

THEMES: dict[str, dict] = {
    "dark": {
        "BG":      "#0f0f13",
        "PANEL":   "#17171f",
        "BORDER":  "#2a2a38",
        "ACCENT":  "#7c5cfc",
        "ACCENT2": "#a78bfa",
        "TAB":     "#4ade80",
        "TEXT":    "#e2e0f0",
        "TEXT2":   "#E0E0E0",
        "SUBTEXT": "#7e7b9a",
        "GREEN":   "#4ade80",
        "RED":     "#f87171",
        "YELLOW":  "#facc15",
        "CYAN":    "#67e8f9",
        "ORANGE":  "#fb923c",
        "STRIPE_COLOURS": None,
    },
    "rich_purple": {
        "BG":      "#0f0f13",
        "PANEL":   "#1f102a",
        "BORDER":  "#2a2a38",
        "ACCENT":  "#9D00FF",
        "ACCENT2": "#b44bff",
        "TAB":     "#4ade80",
        "TEXT":    "#e2e0f0",
        "TEXT2":   "#E0E0E0",
        "SUBTEXT": "#7e7b9a",
        "GREEN":   "#4ade80",
        "RED":     "#f87171",
        "YELLOW":  "#facc15",
        "CYAN":    "#67e8f9",
        "ORANGE":  "#fb923c",
        "STRIPE_COLOURS": None,
    },
    "dark_sand": {
        "BG":      "#1C1D26",
        "PANEL":   "#1f232d",
        "BORDER":  "#353333",
        "ACCENT":  "#FFAC8B",
        "ACCENT2": "#FFC695",
        "TAB":     "#FFC695",
        "TEXT":    "#F5EFE9",
        "TEXT2":   "#E3D8D0",
        "SUBTEXT": "#AE9281",
        "GREEN":   "#4ade80",
        "RED":     "#f87171",
        "YELLOW":  "#facc15",
        "CYAN":    "#67e8f9",
        "ORANGE":  "#FFAC8B",
        "STRIPE_COLOURS": None,
    },
    "absolute_zero": {
        "BG":      "#000D21",
        "PANEL":   "#002154",
        "BORDER":  "#003487",
        "ACCENT":  "#005CED",
        "ACCENT2": "#5496FF",
        "TAB":     "#2177FF",
        "TEXT":    "#EAF3FF",
        "TEXT2":   "#D6E8FF",
        "SUBTEXT": "#A8C4F2",
        "GREEN":   "#4ade80",
        "RED":     "#f87171",
        "YELLOW":  "#facc15",
        "CYAN":    "#67e8f9",
        "ORANGE":  "#fb923c",
        "STRIPE_COLOURS": None,
    },
    "light_purple": {
        "BG":      "#F6E6FA",
        "PANEL":   "#ffffff",
        "BORDER":  "#DDCAE3",
        "ACCENT":  "#9D00FF",
        "ACCENT2": "#b44bff",
        "TAB":     "#000000",
        "TEXT":    "#1a1829",
        "TEXT2":   "#1a1829",
        "SUBTEXT": "#1a1829",
        "GREEN":   "#4ade80",
        "RED":     "#f87171",
        "YELLOW":  "#facc15",
        "CYAN":    "#67e8f9",
        "ORANGE":  "#fb923c",
        "STRIPE_COLOURS": None,
    },
    "light_sand": {
        "BG":      "#fdfbf7",
        "PANEL":   "#f4f1ea",
        "BORDER":  "#e4dfd3",
        "ACCENT":  "#2b5c43",
        "ACCENT2": "#3d7a5a",
        "TAB":     "#000000",
        "TEXT":    "#1c1b18",
        "TEXT2":   "#383630",
        "SUBTEXT": "#706e64",
        "GREEN":   "#15803d",
        "RED":     "#b91c1c",
        "YELLOW":  "#b45309",
        "CYAN":    "#0369a1",
        "ORANGE":  "#c2410c",
        "STRIPE_COLOURS": None,
    },
    "mint": {
        "BG":      "#F5FFFA",
        "PANEL":   "#FFFFFF",
        "BORDER":  "#D6F0E4",
        "ACCENT":  "#2EC4B6",
        "ACCENT2": "#6EE7D8",
        "TAB":     "#1F2937",
        "TEXT":    "#1A2A2A",
        "TEXT2":   "#334155",
        "SUBTEXT": "#64748B",
        "GREEN":   "#22C55E",
        "RED":     "#EF4444",
        "YELLOW":  "#EAB308",
        "CYAN":    "#06B6D4",
        "ORANGE":  "#F97316",
        "STRIPE_COLOURS": None,
    },
    "dark_mint": {
        "BG":      "#0F1C18",
        "PANEL":   "#163129",
        "BORDER":  "#295247",
        "ACCENT":  "#2EC4B6",
        "ACCENT2": "#6EE7D8",
        "TAB":     "#6EE7D8",
        "TEXT":    "#E8FFF9",
        "TEXT2":   "#D3F5EE",
        "SUBTEXT": "#8AB5AB",
        "GREEN":   "#4ADE80",
        "RED":     "#F87171",
        "YELLOW":  "#FACC15",
        "CYAN":    "#67E8F9",
        "ORANGE":  "#FB923C",
        "STRIPE_COLOURS": None,
    },
    "dark_red": {
        "BG":      "#1A0B0B",
        "PANEL":   "#2C1111",
        "BORDER":  "#512121",
        "ACCENT":  "#DC2626",
        "ACCENT2": "#F87171",
        "TAB":     "#F87171",
        "TEXT":    "#FFF1F1",
        "TEXT2":   "#F8DADA",
        "SUBTEXT": "#B48D8D",
        "GREEN":   "#4ADE80",
        "RED":     "#F87171",
        "YELLOW":  "#FACC15",
        "CYAN":    "#67E8F9",
        "ORANGE":  "#FB923C",
        "STRIPE_COLOURS": None,
    },
    "light_red": {
        "BG":      "#FFF5F5",
        "PANEL":   "#FFFFFF",
        "BORDER":  "#F4CACA",
        "ACCENT":  "#DC2626",
        "ACCENT2": "#F87171",
        "TAB":     "#000000",
        "TEXT":    "#2A1111",
        "TEXT2":   "#472020",
        "SUBTEXT": "#735353",
        "GREEN":   "#16A34A",
        "RED":     "#DC2626",
        "YELLOW":  "#CA8A04",
        "CYAN":    "#0284C7",
        "ORANGE":  "#EA580C",
        "STRIPE_COLOURS": None,
    },
    "light_blue": {
        "BG":      "#F2F9FF",
        "PANEL":   "#FFFFFF",
        "BORDER":  "#D2E8F8",
        "ACCENT":  "#3B82F6",
        "ACCENT2": "#60A5FA",
        "TAB":     "#000000",
        "TEXT":    "#172033",
        "TEXT2":   "#2E4468",
        "SUBTEXT": "#6A82A8",
        "GREEN":   "#22C55E",
        "RED":     "#EF4444",
        "YELLOW":  "#EAB308",
        "CYAN":    "#06B6D4",
        "ORANGE":  "#F97316",
        "STRIPE_COLOURS": None,
    },
    "dark_rainbow": {
        "BG":      "#1A1A1A",
        "PANEL":   "#252525",
        "BORDER":  "#444444",
        "ACCENT":  "#E40303",
        "ACCENT2": "#FF8C00",
        "TAB":     "#732982",
        "TEXT":    "#FFFFFF",
        "TEXT2":   "#F0F0F0",
        "SUBTEXT": "#BBBBBB",
        "GREEN":   "#008026",
        "RED":     "#E40303",
        "YELLOW":  "#FFED00",
        "CYAN":    "#004DFF",
        "ORANGE":  "#FF8C00",
        "STRIPE_COLOURS": None,
    },
    "pride_flag": {
        "BG":      "#1A1A1A",
        "PANEL":   "#1c1c1c",
        "BORDER":  "#333333",
        "ACCENT":  "#FFED00",
        "ACCENT2": "#FF8C00",
        "TAB":     "#FFED00",
        "TEXT":    "#FFFFFF",
        "TEXT2":   "#F0F0F0",
        "SUBTEXT": "#CCCCCC",
        "GREEN":   "#008026",
        "RED":     "#E40303",
        "YELLOW":  "#FFED00",
        "CYAN":    "#004DFF",
        "ORANGE":  "#FF8C00",
        "STRIPE_COLOURS": ["#E40303", "#FF8C00", "#FFED00", "#008026", "#004DFF", "#750787"],
    },
    "trans_flag": {
        "BG":      "#0d1f28",
        "PANEL":   "#1a2e36",
        "BORDER":  "#5BCEFA",
        "ACCENT":  "#F5A9B8",
        "ACCENT2": "#5BCEFA",
        "TAB":     "#F5A9B8",
        "TEXT":    "#FFFFFF",
        "TEXT2":   "#e0f4ff",
        "SUBTEXT": "#a8d4e8",
        "GREEN":   "#5BCEFA",
        "RED":     "#F5A9B8",
        "YELLOW":  "#FFFFFF",
        "CYAN":    "#5BCEFA",
        "ORANGE":  "#F5A9B8",
        "STRIPE_COLOURS": ["#5BCEFA", "#F5A9B8", "#FFFFFF", "#F5A9B8", "#5BCEFA"],
    },
    "nonbinary_flag": {
        "BG":      "#1e1230",
        "PANEL":   "#1e1230",
        "BORDER":  "#9C59D1",
        "ACCENT":  "#FFF430",
        "ACCENT2": "#9C59D1",
        "TAB":     "#FFF430",
        "TEXT":    "#FFFFFF",
        "TEXT2":   "#F0F0F0",
        "SUBTEXT": "#DDDDDD",
        "GREEN":   "#9C59D1",
        "RED":     "#FFF430",
        "YELLOW":  "#FFF430",
        "CYAN":    "#FFFFFF",
        "ORANGE":  "#FFF430",
        "STRIPE_COLOURS": ["#FFF430", "#FFFFFF", "#9C59D1", "#2C2C2C"],
    },
    "ace_flag": {
        "BG":      "#161616",
        "PANEL":   "#2a002a",
        "BORDER":  "#800080",
        "ACCENT":  "#B05ACD",
        "ACCENT2": "#CC88EE",
        "TAB":     "#B05ACD",
        "TEXT":    "#FFFFFF",
        "TEXT2":   "#F2F2F2",
        "SUBTEXT": "#CFCFCF",
        "GREEN":   "#B05ACD",
        "RED":     "#f87171",
        "YELLOW":  "#FFFFFF",
        "CYAN":    "#B05ACD",
        "ORANGE":  "#B05ACD",
        "STRIPE_COLOURS": ["#161616", "#808080", "#FFFFFF", "#800080"],
    },
}

THEME_LABELS = {
    "dark":           "Dark",
    "rich_purple":    "Rich Purple",
    "dark_sand":      "Dark Sand",
    "absolute_zero":  "Absolute Zero",
    "light_purple":   "Light Purple",
    "light_sand":     "Light Sand",
    "mint":           "Mint",
    "dark_mint":      "Dark Mint",
    "dark_red":       "Dark Red",
    "light_red":      "Light Red",
    "light_blue":     "Light Blue",
    "dark_rainbow":   "Dark Rainbow",
    "pride_flag":     "Pride Flag",
    "trans_flag":     "Trans Flag",
    "nonbinary_flag": "Nonbinary Flag",
    "ace_flag":       "Ace Flag",
}


def set_theme(mode: str):
    global colour_mode
    palette = THEMES.get(mode, THEMES["rich_purple"])
    colour_mode = mode if mode in THEMES else "new"
    g = globals()
    for key, value in palette.items():
        g[key] = value
    if "STRIPE_COLOURS" not in palette:
        g["STRIPE_COLOURS"] = None



set_theme(colour_mode)